const UNIT_NUMBERS=["11","12","13","14","15","16","17","18","21","22","23","24","25","26","27","28","31","32","33","34","35","36","37","38","41","42","43","44","45","46","47","48","51","52","53","54","55","56","57","58","61","62","63","64","65","66","67","68","71","72","73","74","75","76","77","78","81","82","83","84","85","86","87","88","91","92","93","94","95","96","97","98","101","102","103","104","105","106","107","108","PRINCIPAL"];
const KEY='agua_condominio_v2_data';
const $=id=>document.getElementById(id);
const monthKey=(d=new Date())=>{const y=d.getFullYear(),m=String(d.getMonth()+1).padStart(2,'0');return `${y}-${m}`};
let state=loadState(),selected=null,photoData=null,selectedPeriod=monthKey();
const today=()=>new Date().toISOString().slice(0,10);
const fmt=n=>Number(n||0).toLocaleString('pt-BR',{minimumFractionDigits:2,maximumFractionDigits:2});
function loadState(){try{const data=JSON.parse(localStorage.getItem(KEY))||{readings:[]};data.readings=Array.isArray(data.readings)?data.readings:[];data.references=data.references||{};return data}catch(e){return {readings:[],references:{}}}}
function saveState(){localStorage.setItem(KEY,JSON.stringify(state))}
function periodLabel(p){const [y,m]=p.split('-');return new Date(Number(y),Number(m)-1,1).toLocaleDateString('pt-BR',{month:'long',year:'numeric'})}
function showScreen(id){document.querySelectorAll('.screen').forEach(s=>s.classList.toggle('active',s.id===id));document.querySelectorAll('.bottom-nav button').forEach(b=>b.classList.toggle('active',b.dataset.screen===id));if(id==='dashboard')renderUnitPanel();if(id==='readings')renderUnits();if(id==='history')renderHistory();if(id==='reports')renderReports();if(id==='alerts')renderAlerts();if(id==='references')renderReferences();window.scrollTo({top:0,behavior:'smooth'})}
function unitObj(id){return {id,number:id,type:id==='PRINCIPAL'?'principal':'residencial',meter:state.meters?.[id]||''}}
function currentReading(id,period=selectedPeriod){return state.readings.find(r=>r.unitId===id&&r.period===period)}
function previousReading(id,period=selectedPeriod){const ref=state.references?.[period]?.[id];if(ref!==undefined&&ref!==null&&ref!=='')return Number(ref);const arr=state.readings.filter(r=>r.unitId===id&&r.period<period).sort((a,b)=>b.period.localeCompare(a.period)||String(b.date).localeCompare(String(a.date)));return arr[0]?.current||0}
function allUnits(){return UNIT_NUMBERS.map(unitObj)}
function setPeriod(v){if(!/^\d{4}-\d{2}$/.test(v))return;selectedPeriod=v;$('periodPicker').value=v;$('period').textContent=periodLabel(v);updateDashboard();renderUnitPanel();renderUnits();renderAlerts();renderReports();renderHistory()}
function shiftPeriod(delta){const [y,m]=selectedPeriod.split('-').map(Number);const d=new Date(y,m-1+delta,1);setPeriod(monthKey(d))}
function updateDashboard(){const units=allUnits(),cur=units.map(u=>({u,r:currentReading(u.id)}));const done=cur.filter(x=>x.r).length;let res=0,main=0,alerts=0;cur.forEach(x=>{if(!x.r)return;const c=Number(x.r.current)-Number(x.r.previous);if(c<0)alerts++;if(x.u.type==='principal')main+=Math.max(c,0);else res+=Math.max(c,0)});$('done').textContent=done;$('donePct').textContent=Math.round(done/81*100)+'%';$('pending').textContent=81-done;$('alertCount').textContent=alerts;$('resTotal').textContent=fmt(res)+' m³';$('mainTotal').textContent=fmt(main)+' m³';$('diffTotal').textContent=fmt(main-res)+' m³'}
function renderUnitPanel(){
  const el=$('unitPanel');
  if(!el)return;
  const units=allUnits();
  let done=0;
  el.innerHTML=units.map(u=>{
    const r=currentReading(u.id);
    const c=r?Number(r.current)-Number(r.previous):0;
    const status=!r?'pending':c<0?'alert':'done';
    if(status==='done')done++;
    const label=u.number==='PRINCIPAL'?'PRINCIPAL':u.number;
    const icon=status==='done'?'✓':status==='alert'?'!':'•';
    const title=status==='done'?`Leitura feita • ${fmt(c)} m³`:status==='alert'?'Revisar leitura':'Leitura pendente';
    return `<button class="unit-panel-item ${status}" title="${title}" onclick="openModal('${u.id}')"><span class="unit-panel-number">${label}</span><span class="unit-panel-status">${icon}</span></button>`;
  }).join('');
  $('panelDone').textContent=`${done}/${units.length}`;
}

function renderUnits(){const q=($('search').value||'').toLowerCase(),f=$('filter').value;let list=allUnits().filter(u=>String(u.number).toLowerCase().includes(q)||String(u.meter).toLowerCase().includes(q));list=list.filter(u=>{const r=currentReading(u.id),c=r?Number(r.current)-Number(r.previous):0;if(f==='pending')return !r;if(f==='done')return !!r&&c>=0;if(f==='alert')return !!r&&c<0;return true});$('unitList').innerHTML=list.map(u=>{const r=currentReading(u.id),c=r?Number(r.current)-Number(r.previous):0;const cls=!r?'pending':c<0?'alert':'ok',status=!r?'PENDENTE':c<0?'REVISAR':'REALIZADA';return `<div class="unit"><div><div class="unit-title">${u.number==='PRINCIPAL'?'UNIDADE PRINCIPAL':'UNIDADE '+u.number}</div><div class="unit-meta">${u.type==='principal'?'Medidor principal':'Hidrômetro individual'} ${u.meter?'• '+u.meter:''}</div><span class="status ${cls}">${status}</span>${r?`<div class="unit-meta">Atual: ${fmt(r.current)} m³ • Consumo: ${fmt(c)} m³</div>`:''}</div><button class="${r?'secondary':'primary'}" onclick="openModal('${u.id}')">${r?'Editar':'Ler'}</button></div>`}).join('')||'<div class="panel">Nenhuma unidade encontrada.</div>'}
function openModal(id){selected=unitObj(id);const r=currentReading(id);const appliedPrevious=previousReading(id);photoData=r?.photo||null;$('modalType').textContent=selected.type==='principal'?'MEDIÇÃO PRINCIPAL':'HIDRÔMETRO INDIVIDUAL';$('modalTitle').textContent=selected.number==='PRINCIPAL'?'Unidade Principal':'Unidade '+selected.number;$('readDate').value=r?.date||today();$('prev').value=appliedPrevious;const [py,pm]=selectedPeriod.split('-').map(Number);const prevDate=new Date(py,pm-2,1);const prevPeriod=monthKey(prevDate);$('prevHelp').textContent=`Leitura de ${periodLabel(prevPeriod)}. Campo editável para cadastrar o valor de referência do mês anterior.`;$('current').value=r?.current??'';$('meter').value=r?.meter||selected.meter||'';$('notes').value=r?.notes||'';$('photo').value='';$('photoPreview').innerHTML=photoData?`<img src="${photoData}" alt="Foto do hidrômetro">`:'';$('ocrStatus').textContent='';updateCalc();$('modal').classList.add('show')}
function closeModal(){$('modal').classList.remove('show')}
function updateCalc(){const c=Number($('current').value||0)-Number($('prev').value||0);$('calc').textContent='Consumo: '+fmt(c)+' m³';$('calc').className='calc '+(c<0?'negative':'')}
$('current').addEventListener('input',updateCalc);$('prev').addEventListener('input',updateCalc);
$('photo').addEventListener('change',e=>{const f=e.target.files[0];if(!f)return;const reader=new FileReader();reader.onload=()=>{photoData=reader.result;$('photoPreview').innerHTML=`<img src="${photoData}" alt="Foto do hidrômetro">`};reader.readAsDataURL(f)});
$('ocrBtn').onclick=async()=>{if(!photoData)return toast('Tire ou selecione uma foto primeiro.');if(!window.Tesseract)return toast('OCR indisponível sem internet.');$('ocrStatus').textContent='Lendo o visor…';try{const result=await Tesseract.recognize(photoData,'eng',{logger:m=>{if(m.status==='recognizing text')$('ocrStatus').textContent='OCR '+Math.round(m.progress*100)+'%'}});const nums=(result.data.text.match(/\d+(?:[.,]\d+)?/g)||[]).sort((a,b)=>b.length-a.length);if(nums.length){$('current').value=nums[0].replace(',','.');updateCalc();$('ocrStatus').textContent='Valor sugerido. Confira visualmente antes de salvar.'}else $('ocrStatus').textContent='Não consegui identificar o visor. Informe manualmente.'}catch(e){$('ocrStatus').textContent='Não foi possível executar o OCR.'}};
function saveReading(){const prev=Number($('prev').value||0),cur=Number($('current').value),date=$('readDate').value||today();if(!Number.isFinite(cur)||cur<0)return toast('Informe uma leitura válida.');if(cur<prev&&!confirm('A leitura atual é menor que a anterior. Salvar mesmo assim?'))return;state.meters=state.meters||{};state.meters[selected.id]=$('meter').value.trim();state.references=state.references||{};state.references[selectedPeriod]=state.references[selectedPeriod]||{};state.references[selectedPeriod][selected.id]=prev;const record={unitId:selected.id,period:selectedPeriod,date,previous:prev,current:cur,meter:$('meter').value.trim(),notes:$('notes').value.trim(),photo:photoData||null,savedAt:new Date().toISOString()};const i=state.readings.findIndex(r=>r.unitId===selected.id&&r.period===selectedPeriod);if(i>=0)state.readings[i]=record;else state.readings.push(record);saveState();closeModal();updateDashboard();renderUnitPanel();renderUnits();renderAlerts();renderReports();toast('Leitura salva neste aparelho.')}

function referencePeriod(period=selectedPeriod){const [y,m]=period.split('-').map(Number);return monthKey(new Date(y,m-2,1))}
function renderReferences(){const refPeriod=referencePeriod();$('referencePeriodLabel').textContent=periodLabel(refPeriod);$('targetPeriodLabel').textContent=periodLabel(selectedPeriod);const box=state.references?.[selectedPeriod]||{};const priorReadings={};state.readings.filter(r=>r.period===refPeriod).forEach(r=>priorReadings[r.unitId]=r.current);$('referenceGrid').innerHTML=allUnits().map(u=>{const v=box[u.id]??priorReadings[u.id]??'';const label=u.number==='PRINCIPAL'?'Principal':u.number;return `<label class="reference-cell"><span>${label}</span><input class="reference-input" data-unit="${u.id}" type="number" step="0.01" min="0" inputmode="decimal" value="${v}" placeholder="0,00"></label>`}).join('');$('referenceCount').textContent=`${Object.values(box).filter(v=>v!==''&&v!==null&&v!==undefined).length}/81 preenchidas`}
function saveReferences(){state.references=state.references||{};state.references[selectedPeriod]=state.references[selectedPeriod]||{};const refs=state.references[selectedPeriod];document.querySelectorAll('.reference-input').forEach(input=>{const id=input.dataset.unit;const raw=input.value.trim();if(raw==='')delete refs[id];else{const n=Number(raw.replace(',','.'));if(Number.isFinite(n)&&n>=0)refs[id]=n}});state.readings.forEach(r=>{if(r.period===selectedPeriod&&Object.prototype.hasOwnProperty.call(refs,r.unitId)){r.previous=Number(refs[r.unitId]);}});saveState();renderReferences();updateDashboard();renderUnitPanel();renderUnits();renderAlerts();renderReports();toast('Referências aplicadas ao mês '+periodLabel(selectedPeriod)+'.')}
function fillReferencesFromPreviousMonth(){const refPeriod=referencePeriod();state.references=state.references||{};state.references[selectedPeriod]=state.references[selectedPeriod]||{};const refs=state.references[selectedPeriod];let count=0;state.readings.filter(r=>r.period===refPeriod).forEach(r=>{refs[r.unitId]=Number(r.current);count++});state.readings.forEach(r=>{if(r.period===selectedPeriod&&Object.prototype.hasOwnProperty.call(refs,r.unitId)){r.previous=Number(refs[r.unitId]);}});saveState();renderReferences();updateDashboard();renderUnitPanel();renderUnits();renderAlerts();renderReports();toast(count?`${count} leituras do mês anterior carregadas e aplicadas.`:'Não há leituras do mês anterior para carregar.')}
function renderHistory(){const q=($('historySearch').value||'').toLowerCase();const rows=state.readings.filter(r=>r.unitId.toLowerCase().includes(q)).sort((a,b)=>b.period.localeCompare(a.period)||b.savedAt.localeCompare(a.savedAt));$('historyList').innerHTML=rows.length?rows.map(r=>{const c=Number(r.current)-Number(r.previous);return `<div class="history-item"><b>${r.unitId==='PRINCIPAL'?'UNIDADE PRINCIPAL':'UNIDADE '+r.unitId}</b><div class="unit-meta">${periodLabel(r.period)} • ${r.date} • anterior ${fmt(r.previous)} • atual ${fmt(r.current)}</div><div><strong>Consumo: ${fmt(c)} m³</strong>${r.notes?` • ${r.notes}`:''}</div></div>`}).join(''):'<div class="panel">Nenhuma leitura registrada ainda.</div>'}
function averageConsumption(id,excludePeriod=null){const vals=state.readings.filter(r=>r.unitId===id&&r.period!==excludePeriod&&Number(r.current)>=Number(r.previous)).map(r=>Number(r.current)-Number(r.previous));return vals.length?vals.reduce((a,b)=>a+b,0)/vals.length:null}
function renderAlerts(){const rows=allUnits().map(u=>{const r=currentReading(u.id);if(!r)return null;const c=Number(r.current)-Number(r.previous);const avg=averageConsumption(u.id,selectedPeriod);if(c<0)return {u,r,c,kind:'negative',text:'Leitura atual menor que a anterior.'};if(avg!==null&&avg>0&&c>avg*1.5)return {u,r,c,kind:'high',text:`Consumo ${Math.round(c/avg*100)}% da média histórica (${fmt(avg)} m³).`};if(c===0)return {u,r,c,kind:'zero',text:'Consumo zerado no período.'};return null}).filter(Boolean);$('alertsList').innerHTML=rows.length?rows.map(x=>`<div class="history-item"><span class="status alert">${x.kind==='negative'?'REVISAR':'ATENÇÃO'}</span><h3>${x.u.number==='PRINCIPAL'?'Unidade Principal':'Unidade '+x.u.number}</h3><div class="unit-meta">Consumo ${fmt(x.c)} m³ • ${x.text}</div></div>`).join(''):'<div class="panel"><b>✓ Nenhum alerta automático neste período.</b><p class="muted">Os alertas usam as leituras disponíveis no aparelho.</p></div>'}
function reportData(period=selectedPeriod){const residential=[],main=currentReading('PRINCIPAL',period);allUnits().filter(u=>u.type==='residencial').forEach(u=>{const r=currentReading(u.id,period);if(r)residential.push({unit:u.number,consumption:Number(r.current)-Number(r.previous),current:Number(r.current),previous:Number(r.previous)})});const res=residential.reduce((s,x)=>s+Math.max(x.consumption,0),0);const mainC=main?Math.max(Number(main.current)-Number(main.previous),0):0;return {residential,main, res,mainC,diff:mainC-res,done:residential.length+(main?1:0)}}
function renderReports(){const d=reportData();$('rDone').textContent=d.done;$('rRes').textContent=fmt(d.res)+' m³';$('rMain').textContent=fmt(d.mainC)+' m³';$('rAlerts').textContent=Number($('alertCount').textContent||0);$('lossM3').textContent=fmt(d.diff)+' m³';$('lossPct').textContent=d.mainC>0?fmt(d.diff/d.mainC*100)+'%':'—';$('reportPeriod').textContent=periodLabel(selectedPeriod);drawChart(d.residential)}
function drawChart(rows){const c=$('consumptionChart'),ctx=c.getContext('2d');const dpr=window.devicePixelRatio||1,w=c.clientWidth||600,h=260;c.width=w*dpr;c.height=h*dpr;ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,w,h);if(!rows.length){ctx.font='16px sans-serif';ctx.fillText('Ainda não há leituras residenciais neste período.',20,40);return}const top=20,bottom=45,left=38,right=10,plotW=w-left-right,plotH=h-top-bottom,max=Math.max(...rows.map(r=>r.consumption),1);ctx.font='11px sans-serif';ctx.strokeStyle='#d9e2ec';ctx.fillStyle='#0b5cab';const barW=Math.max(4,plotW/rows.length*.62);rows.forEach((r,i)=>{const x=left+i*(plotW/rows.length)+(plotW/rows.length-barW)/2;const bh=Math.max(1,r.consumption/max*plotH);ctx.fillRect(x,top+plotH-bh,barW,bh);if(rows.length<=20||i%5===0){ctx.fillStyle='#344054';ctx.fillText(r.unit,x,top+plotH+18);ctx.fillStyle='#0b5cab'}});ctx.fillStyle='#344054';ctx.fillText('Consumo por unidade (m³)',left,14)}
function exportCSV(){const rows=[['Unidade','Tipo','Período','Data','Anterior (m³)','Atual (m³)','Consumo (m³)','Hidrômetro','Observações']];allUnits().forEach(u=>{const r=currentReading(u.id);if(r)rows.push([u.number,u.type,r.period,r.date,r.previous,r.current,(Number(r.current)-Number(r.previous)).toFixed(2),r.meter||'',r.notes||''])});const csv=rows.map(row=>row.map(v=>`"${String(v).replaceAll('"','""')}"`).join(';')).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob(['\ufeff'+csv],{type:'text/csv;charset=utf-8'}));a.download='leituras-agua-'+selectedPeriod+'.csv';a.click()}
function backupJSON(){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(state,null,2)],{type:'application/json'}));a.download='backup-leituras-agua-'+today()+'.json';a.click();toast('Backup criado.')}
function openReferences(){showScreen('references');renderReferences();}

$('referenceSaveBtn').addEventListener('click',saveReferences);$('referenceFillBtn').addEventListener('click',fillReferencesFromPreviousMonth);$('openReferencesBtn').addEventListener('click',openReferences);$('restore').addEventListener('change',e=>{const f=e.target.files[0];if(!f)return;const rd=new FileReader();rd.onload=()=>{try{const data=JSON.parse(rd.result);if(!Array.isArray(data.readings))throw Error();state=data;saveState();updateDashboard();renderUnitPanel();renderUnits();renderAlerts();renderReports();toast('Backup restaurado.')}catch(x){toast('Arquivo de backup inválido.')}};rd.readAsText(f)});
function clearAll(){if(confirm('Apagar TODAS as leituras e referências deste aparelho? Esta ação não pode ser desfeita.')){localStorage.removeItem(KEY);state={readings:[],references:{}};updateDashboard();renderUnitPanel();renderUnits();renderAlerts();renderReports();toast('Dados apagados.')}}
function printReport(){showScreen('reports');setTimeout(()=>window.print(),100)}
function toast(t){const el=$('toast');el.textContent=t;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2300)}
$('periodPicker').value=selectedPeriod;$('period').textContent=periodLabel(selectedPeriod);renderReferences();updateDashboard();renderUnitPanel();renderUnits();renderAlerts();renderReports();
if('serviceWorker' in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));
