create extension if not exists pgcrypto;
create table if not exists public.units(id text primary key,number text unique not null,type text not null check(type in ('residencial','principal')),meter_id text,resident_name text,created_at timestamptz default now());
create table if not exists public.profiles(id uuid primary key references auth.users(id) on delete cascade,name text,role text default 'leiturista' check(role in ('admin','leiturista','consulta')),created_at timestamptz default now());
create table if not exists public.readings(id uuid primary key default gen_random_uuid(),unit_id text references public.units(id) on delete cascade,reading_date date not null,period text not null,previous_reading numeric(12,2) default 0,current_reading numeric(12,2) not null,consumption numeric(12,2) generated always as(current_reading-previous_reading) stored,meter_id text,notes text,user_id uuid references auth.users(id),created_at timestamptz default now(),updated_at timestamptz default now(),unique(unit_id,period));
alter table public.units enable row level security; alter table public.profiles enable row level security; alter table public.readings enable row level security;
create or replace function public.new_profile() returns trigger language plpgsql security definer set search_path=public as $$ begin insert into public.profiles(id,name) values(new.id,new.email) on conflict do nothing; return new; end $$;
drop trigger if exists new_user_profile on auth.users; create trigger new_user_profile after insert on auth.users for each row execute procedure public.new_profile();
create policy "units authenticated read" on public.units for select to authenticated using(true);
create policy "profiles own read" on public.profiles for select to authenticated using(id=auth.uid() or exists(select 1 from public.profiles p where p.id=auth.uid() and p.role='admin'));
create policy "readings authenticated read" on public.readings for select to authenticated using(true);
create policy "readings own insert" on public.readings for insert to authenticated with check(user_id=auth.uid());
create policy "readings own update" on public.readings for update to authenticated using(user_id=auth.uid() or exists(select 1 from public.profiles p where p.id=auth.uid() and p.role='admin'));
insert into public.units(id,number,type) values
('11','11','residencial'),('12','12','residencial'),('13','13','residencial'),('14','14','residencial'),('15','15','residencial'),('16','16','residencial'),('17','17','residencial'),('18','18','residencial'),('21','21','residencial'),('22','22','residencial'),('23','23','residencial'),('24','24','residencial'),('25','25','residencial'),('26','26','residencial'),('27','27','residencial'),('28','28','residencial'),('31','31','residencial'),('32','32','residencial'),('33','33','residencial'),('34','34','residencial'),('35','35','residencial'),('36','36','residencial'),('37','37','residencial'),('38','38','residencial'),('41','41','residencial'),('42','42','residencial'),('43','43','residencial'),('44','44','residencial'),('45','45','residencial'),('46','46','residencial'),('47','47','residencial'),('48','48','residencial'),('51','51','residencial'),('52','52','residencial'),('53','53','residencial'),('54','54','residencial'),('55','55','residencial'),('56','56','residencial'),('57','57','residencial'),('58','58','residencial'),('61','61','residencial'),('62','62','residencial'),('63','63','residencial'),('64','64','residencial'),('65','65','residencial'),('66','66','residencial'),('67','67','residencial'),('68','68','residencial'),('71','71','residencial'),('72','72','residencial'),('73','73','residencial'),('74','74','residencial'),('75','75','residencial'),('76','76','residencial'),('77','77','residencial'),('78','78','residencial'),('81','81','residencial'),('82','82','residencial'),('83','83','residencial'),('84','84','residencial'),('85','85','residencial'),('86','86','residencial'),('87','87','residencial'),('88','88','residencial'),('91','91','residencial'),('92','92','residencial'),('93','93','residencial'),('94','94','residencial'),('95','95','residencial'),('96','96','residencial'),('97','97','residencial'),('98','98','residencial'),('101','101','residencial'),('102','102','residencial'),('103','103','residencial'),('104','104','residencial'),('105','105','residencial'),('106','106','residencial'),('107','107','residencial'),('108','108','residencial'),('principal','UNIDADE PRINCIPAL','principal') on conflict(id) do nothing;
-- Depois de criar o primeiro usuário, promova-o: update public.profiles set role='admin' where id='UUID';